/* This file was generated by SableCC (http://www.sablecc.org/). */

package funlang.syntax.node;

import funlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class AAddArith extends PArith
{
    private PArith _arith_;
    private TPlus _plus_;
    private PFac _fac_;

    public AAddArith()
    {
        // Constructor
    }

    public AAddArith(
        @SuppressWarnings("hiding") PArith _arith_,
        @SuppressWarnings("hiding") TPlus _plus_,
        @SuppressWarnings("hiding") PFac _fac_)
    {
        // Constructor
        setArith(_arith_);

        setPlus(_plus_);

        setFac(_fac_);

    }

    @Override
    public Object clone()
    {
        return new AAddArith(
            cloneNode(this._arith_),
            cloneNode(this._plus_),
            cloneNode(this._fac_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAddArith(this);
    }

    public PArith getArith()
    {
        return this._arith_;
    }

    public void setArith(PArith node)
    {
        if(this._arith_ != null)
        {
            this._arith_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arith_ = node;
    }

    public TPlus getPlus()
    {
        return this._plus_;
    }

    public void setPlus(TPlus node)
    {
        if(this._plus_ != null)
        {
            this._plus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._plus_ = node;
    }

    public PFac getFac()
    {
        return this._fac_;
    }

    public void setFac(PFac node)
    {
        if(this._fac_ != null)
        {
            this._fac_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fac_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arith_)
            + toString(this._plus_)
            + toString(this._fac_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arith_ == child)
        {
            this._arith_ = null;
            return;
        }

        if(this._plus_ == child)
        {
            this._plus_ = null;
            return;
        }

        if(this._fac_ == child)
        {
            this._fac_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arith_ == oldChild)
        {
            setArith((PArith) newChild);
            return;
        }

        if(this._plus_ == oldChild)
        {
            setPlus((TPlus) newChild);
            return;
        }

        if(this._fac_ == oldChild)
        {
            setFac((PFac) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
