/* This file was generated by SableCC (http://www.sablecc.org/). */

package funlang.syntax.node;

import java.util.*;
import funlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class AArgs extends PArgs
{
    private PArg _arg_;
    private final LinkedList<PAdditionalArg> _additionalArgs_ = new LinkedList<PAdditionalArg>();

    public AArgs()
    {
        // Constructor
    }

    public AArgs(
        @SuppressWarnings("hiding") PArg _arg_,
        @SuppressWarnings("hiding") List<?> _additionalArgs_)
    {
        // Constructor
        setArg(_arg_);

        setAdditionalArgs(_additionalArgs_);

    }

    @Override
    public Object clone()
    {
        return new AArgs(
            cloneNode(this._arg_),
            cloneList(this._additionalArgs_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgs(this);
    }

    public PArg getArg()
    {
        return this._arg_;
    }

    public void setArg(PArg node)
    {
        if(this._arg_ != null)
        {
            this._arg_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arg_ = node;
    }

    public LinkedList<PAdditionalArg> getAdditionalArgs()
    {
        return this._additionalArgs_;
    }

    public void setAdditionalArgs(List<?> list)
    {
        for(PAdditionalArg e : this._additionalArgs_)
        {
            e.parent(null);
        }
        this._additionalArgs_.clear();

        for(Object obj_e : list)
        {
            PAdditionalArg e = (PAdditionalArg) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._additionalArgs_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arg_)
            + toString(this._additionalArgs_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arg_ == child)
        {
            this._arg_ = null;
            return;
        }

        if(this._additionalArgs_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arg_ == oldChild)
        {
            setArg((PArg) newChild);
            return;
        }

        for(ListIterator<PAdditionalArg> i = this._additionalArgs_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAdditionalArg) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
