/* This file was generated by SableCC (http://www.sablecc.org/). */

package funlang.syntax.node;

import funlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class AExpoPow extends PPow
{
    private PTerm _term_;
    private TCaret _caret_;
    private PPow _pow_;

    public AExpoPow()
    {
        // Constructor
    }

    public AExpoPow(
        @SuppressWarnings("hiding") PTerm _term_,
        @SuppressWarnings("hiding") TCaret _caret_,
        @SuppressWarnings("hiding") PPow _pow_)
    {
        // Constructor
        setTerm(_term_);

        setCaret(_caret_);

        setPow(_pow_);

    }

    @Override
    public Object clone()
    {
        return new AExpoPow(
            cloneNode(this._term_),
            cloneNode(this._caret_),
            cloneNode(this._pow_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpoPow(this);
    }

    public PTerm getTerm()
    {
        return this._term_;
    }

    public void setTerm(PTerm node)
    {
        if(this._term_ != null)
        {
            this._term_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._term_ = node;
    }

    public TCaret getCaret()
    {
        return this._caret_;
    }

    public void setCaret(TCaret node)
    {
        if(this._caret_ != null)
        {
            this._caret_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._caret_ = node;
    }

    public PPow getPow()
    {
        return this._pow_;
    }

    public void setPow(PPow node)
    {
        if(this._pow_ != null)
        {
            this._pow_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pow_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._term_)
            + toString(this._caret_)
            + toString(this._pow_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._term_ == child)
        {
            this._term_ = null;
            return;
        }

        if(this._caret_ == child)
        {
            this._caret_ = null;
            return;
        }

        if(this._pow_ == child)
        {
            this._pow_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._term_ == oldChild)
        {
            setTerm((PTerm) newChild);
            return;
        }

        if(this._caret_ == oldChild)
        {
            setCaret((TCaret) newChild);
            return;
        }

        if(this._pow_ == oldChild)
        {
            setPow((PPow) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
