/* This file was generated by SableCC (http://www.sablecc.org/). */

package funlang.syntax.node;

import funlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleExp extends PExp
{
    private PArith _arith_;

    public ASimpleExp()
    {
        // Constructor
    }

    public ASimpleExp(
        @SuppressWarnings("hiding") PArith _arith_)
    {
        // Constructor
        setArith(_arith_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleExp(
            cloneNode(this._arith_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleExp(this);
    }

    public PArith getArith()
    {
        return this._arith_;
    }

    public void setArith(PArith node)
    {
        if(this._arith_ != null)
        {
            this._arith_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._arith_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._arith_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._arith_ == child)
        {
            this._arith_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._arith_ == oldChild)
        {
            setArith((PArith) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
