/* This file was generated by SableCC (http://www.sablecc.org/). */

package funlang.syntax.node;

import funlang.syntax.analysis.*;

@SuppressWarnings("nls")
public final class ASimpleFac extends PFac
{
    private PPow _pow_;

    public ASimpleFac()
    {
        // Constructor
    }

    public ASimpleFac(
        @SuppressWarnings("hiding") PPow _pow_)
    {
        // Constructor
        setPow(_pow_);

    }

    @Override
    public Object clone()
    {
        return new ASimpleFac(
            cloneNode(this._pow_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASimpleFac(this);
    }

    public PPow getPow()
    {
        return this._pow_;
    }

    public void setPow(PPow node)
    {
        if(this._pow_ != null)
        {
            this._pow_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pow_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pow_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pow_ == child)
        {
            this._pow_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pow_ == oldChild)
        {
            setPow((PPow) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
